BeeKeeper/trunk/BeeKeeper/beekeeper/urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.contrib.auth.views import login, logout

# Uncomment the next two lines to enable the admin:


urlpatterns = patterns('',
    (r'css/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.CSS_BEEKEEPER_ROOT, 'show_indexes': False}),
    (r'media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': False}),
    (r'images/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.IMAGES_BEEKEEPER_ROOT, 'show_indexes': False}),
    (r'js/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.JS_BEEKEEPER_ROOT, 'show_indexes': False}),
)

urlpatterns += patterns('BeeKeeper.beekeeper.views',
    (r'^login/$',  login),
    (r'^logout/$', logout),
    
    (r'show_form_list/$', 'showFormList'),
    (r'show_form/(?P<formid>\d+)/$', 'showForm'),
    (r'show_form_statistics/(?P<formid>\d+)/$', 'showFormStatistics'),
    (r'create_form_field_statistics/(?P<formid>\d+)/(?P<formfieldid>\d+)/$', 'createFormFieldStatistics'),
    (r'delete_form/(?P<formid>\d+)/$', 'deleteForm'),
    (r'show_instance_list/(?P<formid>\d+)/$', 'showInstanceList'),
    (r'show_instances_map/(?P<formid>\d+)/$', 'showInstancesMap'),
    (r'show_instance/(?P<instanceid>\d+)/$', 'showInstance'),
    (r'show_instance_map/(?P<instanceid>\d+)/$', 'showInstanceMap'),
    (r'delete_instance/(?P<instanceid>\d+)/$', 'deleteInstance'),
    (r'^$', 'showFormList'),
)

BeeKeeper/trunk/BeeKeeper/urls.py
from django.conf.urls.defaults import *



from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    # Example:
    #(r'^BeeKeeper/', include('BeeKeeper.foo.urls')),
    
    (r'^db_models/', include('BeeKeeper.db_models.urls')),
    
    (r'^form_xml2db_parser/', include('BeeKeeper.form_xml2db_parser.urls')),

    (r'^instance_xml2db_parser/', include('BeeKeeper.instance_xml2db_parser.urls')),
    
    #(r'^beekeeper/', include('beekeeper.urls')),
    
    (r'^ws_server/', include('BeeKeeper.ws_server.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
    
    (r'^accounts/', include('BeeKeeper.beekeeper.urls')),

    # Se supone que acá va a ir la web
    (r'^$', include('BeeKeeper.beekeeper.urls')),
)

BeeKeeper/trunk/BeeKeeper/beekeeper/models.py
from django.db import models

# Create your models here.

BeeKeeper/trunk/BeeKeeper/db_models/models.py
"""*Database Models* definition module. 
   :author: Francisco Jose Cabrera Hernandez,
            Nicolas Pernas Maradei,
            Romen Rodriguez Gil
   :version: 0.2"""

# Imports
from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.db.models.query import QuerySet


#from django.core.management.validation import max_length

#--------------------------------------
# Models classes
#--------------------------------------

class Form(models.Model):
    """Class: `Form`. 
       :param name: form name. 
       :param version: form version.
       :param xml: form XML.
       :todo: Add the schema_path to the XML"""
    descripcion = models.CharField(max_length = 2048, null=True)
    name = models.CharField(max_length = 256)
    version = models.SmallIntegerField()
    xml = models.CharField(max_length = 16192)#, unique=True)
    active = models.BooleanField()
    geolocalized = models.BooleanField()
    creation_date = models.DateField()

    class Meta:
        unique_together = ('name', 'version')
        ordering = ['name']

    def __unicode__(self):
        return unicode(self.name)



class Section(models.Model):
    """Class: `Section`. 
       :param name: section name. 
       :param order: section order inside a form.
       :param form: references the form in which this section is."""
    name = models.CharField(max_length = 128)
    order = models.SmallIntegerField()
    form = models.ForeignKey(Form)

    class Meta:
        unique_together = (('name', 'form'), ('order', 'form'))
        ordering = ['form']

    def __unicode__(self):
        return unicode(self.name)



class FieldGroup(models.Model):
    """Class: `FieldGroup`. 
       :param label: Field-group label in the form.
       :param multiple: If it is a list of elements"""
    label = models.CharField(max_length = 256)
    multiple = models.BooleanField()
    required = models.BooleanField()

    def __unicode__(self):
        return unicode(self.label)



class FormField(models.Model):
    """Class: `FormField`. 
       :param label: Field label in the form.
       :param section_order: The order of the field in the current section.
       :param section: The current section.
       :param field_group: A Field could belong to a group.
       :param field_group_order: The order of the field in the group (if any).
       :param type: Normal or special type
       :param required: True/False
       :attention The field_group_order is an attribute here
                  because Django that not allow us to have
                  an attribute in a 1:N relationship.
                  The problem is that it will have a lot of null values
        :attention A Field could not belong to a group"""
    label = models.CharField(max_length = 256)
    # Section
    section_order = models.SmallIntegerField()
    section = models.ForeignKey(Section)
    # Groups
    field_group = models.ForeignKey(FieldGroup, null = True)
    field_group_order = models.SmallIntegerField(null = True)
    type = models.CharField(max_length = 128)
    required = models.BooleanField()

    class Meta:
        unique_together = ('section', 'section_order')
        ordering = ['section']

    def __unicode__(self):
        return unicode(self.label)


class FieldOption(models.Model):
    """Class: `FieldOption`.
       :param label: Option label in the field.
       :param value: Value of the option
       :param form_field: The form field which is related to this option """
    label = models.CharField(max_length = 256)
    value = models.CharField(max_length = 128)
    # Link
    form_field = models.ForeignKey(FormField, null = True)

    class Meta:
        unique_together = (('label', 'form_field'), ('value', 'form_field'))
        ordering = ['form_field']
        
    def __unicode__(self):
        return unicode(self.label)


class Property(models.Model):
    """Class: `Property`. 
       :param name: Property name for the field.
       :param value: Value of the property
       :param form_field: The form field which is related to this option """
    name = models.CharField(max_length = 256)
    value = models.CharField(max_length = 128)
    # Link
    form_field = models.ForeignKey(FormField, null = True)
    group_field = models.ForeignKey(FieldGroup, null = True)

       
    def __unicode__(self):
        if self.form_field:
            return u'%s - %s' %(self.form_field.label, self.name)
        else:
            return u'%s - %s' %(self.group_field.label, self.name)



class Instance(models.Model):
    """Class: `Instance`. 
       :param creation_date: Instance creation date.
       :param modification_date: Instance modification date.
       :param signature: User signature.
       :param form: form of this instance.
       :attention Signature may be replaced by username
       :todo Signature"""
    creation_date = models.DateField()
    modification_date = models.DateField()
    signature = models.CharField(max_length = 128, null=True)
    imei = models.CharField(max_length = 16, null=True)
    longitude = models.CharField(max_length = 32, null=True)
    latitude = models.CharField(max_length = 32, null=True)
    form = models.ForeignKey(Form)
    completed = models.BooleanField()
    xml = models.CharField(max_length = 16192)

    def __unicode__(self):
        return u'%s - %s' %(self.form.name, self.id)



class SubclassingQuerySet(QuerySet):
    def __getitem__(self, k):
        result = super(SubclassingQuerySet, self).__getitem__(k)
        if isinstance(result, models.Model) :
            return result.as_leaf_class()
        else :
            return result
    def __iter__(self):
        for item in super(SubclassingQuerySet, self).__iter__():
            yield item.as_leaf_class()


class InstanceFieldManager(models.Manager):
    def get_query_set(self):
        return SubclassingQuerySet(self.model)




class InstanceField(models.Model):
    """Class: `InstanceField`. 
       :param instance: Instance which this field (value) is related to.
       :param instance_order: Order of this field in the instance.
       :param form_fields: form-field related with this instance-field.
       :attention instance_order is different of field_order because
                  of the dynamic fields"""
    instance = models.ForeignKey(Instance)
    instance_order = models.SmallIntegerField()
    form_field = models.ForeignKey(FormField)
    objects = InstanceFieldManager()

    content_type = models.ForeignKey(ContentType,editable=False,null=True)


    def save(self, *args, **kwargs):
        if(not self.content_type):
            self.content_type = ContentType.objects.get_for_model(self.__class__)
            super(InstanceField, self).save(*args, **kwargs)

    def as_leaf_class(self):
        content_type = self.content_type
        model = content_type.model_class()
        if (model == InstanceField):
            return self
        return model.objects.get(id=self.id)

    class Meta:
        unique_together = ('instance', 'instance_order')
        ordering = ['instance']
        #abstract = True

    def __unicode__(self):
        return u'%s - %s' %(self.form_field.label, self.id)




class TextField(InstanceField):
    """Class: `TextField`. 
       :param value: The text itself."""
    value = models.CharField(max_length = 128)
    objects = InstanceFieldManager()

    def __unicode__(self):
        return unicode(self.value)
    
    def get_text(self):
        return unicode(self.value)
    
    
class TextAreaField(InstanceField):
    """Class: `TextAreaField`. 
       :param value: The text itself."""
    value = models.CharField(max_length = 1024)
    objects = InstanceFieldManager()

    def __unicode__(self):
        return unicode(self.value)
    
    def get_text(self):
        return unicode(self.value)


class NumericField(InstanceField):
    """Class: `TextField`. 
       :param value: The text itself."""
    value = models.IntegerField()
    objects = InstanceFieldManager()

    def __unicode__(self):
        return unicode(self.value)
    
    def get_text(self):
        return unicode(self.value)


class DateField(InstanceField):
    """Class: `DateField`. 
       :param day_value: The Day.
       :param month_value: The Month.
       :param year_value: The Year."""
    value = models.DateField()
    objects = InstanceFieldManager()

    def __unicode__(self):
        return unicode(self.value)
    
    def get_text(self):
        return unicode(self.value)


class RadioField(InstanceField):
    """Class: `RadioField`. 
       :param value: The id of the selected option."""
    value = models.CharField(max_length = 16) # TIPO DE DATOS ID DE DJANGO
    objects = InstanceFieldManager()

    def __unicode__(self):
        return unicode(self.value)
    
    def get_text(self):
        return unicode(self.value)
    
    
class CheckField(InstanceField):
    """Class: `CheckField`. 
       :param value: True or False (if TRIESTATE property also None)."""
    value = models.CharField(max_length = 5) # TIPO DE DATOS ID DE DJANGO
    objects = InstanceFieldManager()

    def __unicode__(self):
        return unicode(self.value)
    
    def get_text(self):
        return unicode(self.value)
    
    
class ComboField(InstanceField):
    """Class: `ComboField`. 
       :param value: The id of the selected option."""
    value = models.CharField(max_length = 5) # TIPO DE DATOS ID DE DJANGO
    objects = InstanceFieldManager()

    def __unicode__(self):
        return unicode(self.value)
    
    def get_text(self):
        return unicode(self.value)



class ImageField(InstanceField):
    """Class: `ImageField`. 
       :param value: The image itself.
       :todo ImageField parameters"""
    value = models.ImageField(upload_to = 'images')
    objects = InstanceFieldManager()

    def __unicode__(self):
        return unicode(self.value)
    
    def get_text(self):

BeeKeeper/trunk/BeeKeeper/beekeeper/templates/base.html
{% comment %}
Esquema basico de la web.
Project: Seed::Modeler
Author: Francisco Jose Cabrera Hernandez,
        Nicolas Pernas Maradei,
        Romen Rodriguez Gil
{% endcomment %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<title>Turawet Administrador: | {% block title %}{% endblock %}</title>
	<link rel="icon" href="/beekeeper/images/turawet_favicon.ico" type="image/x-icon">
    <link rel="shortcut icon" href="/beekeeper/images/turawet_favicon.ico" type="image/x-icon"> 
	<link rel="stylesheet" href="/beekeeper/css/default.css" />
	<!-- No consigo poner rutas absoultas y que funcion en ver_formulario el CSS -->
</head>
<body>
    <div id="containt">
        <div id="form">
            {% block mainframe %}
            {% endblock %}
        </div>
        
        <div id="resultado">
            <img class="delete" src="/beekeeper/images/buttons/delete.png" onClick="hideResults()"/>
            {% block result %}
            {% endblock %}
        </div>
        
        <div id="sections">
            {% block sectionslinks %}
            {% endblock %}
        </div>

        <div id="fieldsBar">
            {% block sidebar %}
            {% endblock %}
            <div class="buttons">
                {% block buttonssidebar %}
                {% endblock %}
            </div>  
        </div>      
        <a href="http://www.turawetproject.org"><img src="/beekeeper/images/tw_beekeeper_logo.png" id="minilogo"/></a>
    </div>
    <script src="/beekeeper/js/lib/jquery.min.js"></script>
    <script src="/beekeeper/js/hide_results.js"></script>
    <script src="/beekeeper/js/expand_field.js"></script>
    <script src="/beekeeper/js/select_section.js"></script>
    <script src="/beekeeper/js/fieldlabels.js"></script>
    {% block extrajs %}
    {% comment %}
        Librerías externas Javascript (JQuery y plugins)
        
        Falta crear la carpeta JS y añadirla al settings y al beekeeper.urls
    {% endcomment %}
    {% endblock %}
</body>
</html>

BeeKeeper/trunk/BeeKeeper/beekeeper/templates/index.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Turawet Project</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" href="http://www.turawetproject.org/beekeeper/css/index.css" type="text/css" />
</head>
    <body>
			<div class="main">
				<h1 class="title"> Turawet Project</h1>
	            <p><img src="http://www.turawetproject.org/beekeeper/images/turawet_logo.png"/></p>
	            <h3><em>Comming soon</em></h3>
            </div>

    </body>
</html>

BeeKeeper/trunk/BeeKeeper/beekeeper/templates/ver_estadisticas_formulario.html
{% extends "base.html" %}
{% block title %}Formularios{% endblock %}
{% block mainframe %}

			{% if form %}
				<h1>Formulario: {{ form.name }}</h1>
				<h3>Estad&iacute;sticas</h3>
				
				
				
				{% for section in form.section_set.all %}
					 <ul id="s{{ section.id }}" class="section" href="#s{{ section.id }}">
					   <p class="sectionlabel">{{ section.name }}</p>
					   {% for field in section.formfield_set.all %}
					   		{% if field.type == "RADIO" or field.type == "COMBO" %}
		                       <li id="f{{ field.id }}" class="{{ field.type|lower }}">
									<div class="actions">
										<img src="/beekeeper/images/buttons/more.png" onclick="javascript:expandField('f{{ field.id }}')" class="fieldButton">
									</div>
									<p class="fieldlabel">{{ field.label }}</p>
									
			                       {% if field.fieldoption_set.all %}
										<div class="options">
											<img class="statistic" src="/beekeeper/create_form_field_statistics/{{ form.id }}/{{ field.id }}" class="statisticImage" />
										   {% for option in field.fieldoption_set.all %}
												<p>{{ option.label }}: {{ option.value }}</p>		                       		
										   {% endfor %}
				                       	</div>
			                       {% endif %}
		                       </li>
	                       {% endif %}
					   {% endfor %}
					</ul>
				{% endfor %}
				
				
				
				
				<!--<img src="/beekeeper/images/{{ filename }}" class="fieldButton" />-->
				<br/>
			{% else %}
				<h3>No se ha encontrado el formulario en la base de datos.</h3>
			{% endif %}

{% endblock %}


{% block sidebar %}
		    <ul>
				<li><a class="item" href="/beekeeper/show_form_list/" id="campo0">
					<img src="/beekeeper/images/tw_back.png" />
					<div class="label">
						<p><strong>Volver atr&aacute;s</strong></p>
					</div>
				</a></li>	
			</ul>
{% endblock %}


{% block sectionslinks %}
	<ul>
	{% for section in form.section_set.all %}
		<li id="s{{ section.id }}link">
			<a href="#s{{ section.id }}" onclick="selectSection('s{{ section.id }}')">
				Sección {{ section.order }}
			</a>
		</li>
	{% endfor %}
	</ul>
	
{% endblock %}

BeeKeeper/trunk/BeeKeeper/beekeeper/templates/ver_formulario.html
{% extends "base.html" %}
{% block title %}Formularios{% endblock %}
{% block mainframe %}

			{% if form %}
				<h1>Formulario: {{ form.id }}</h1>
				<h2>{{ form.name }}</h2>

				<ul id="s-1" class="section" href="#s-1">
				   <p class="sectionlabel">Metadatos</p>
				   	{% if form.creation_date %}
					  	<p class="metadata">Fecha de creaci&oacute;n: <span class="metavalue">{{ form.creation_date }}</span></p>
					{% endif %}
				   	{% if form.geolocalized %}
					  	<p class="metadata">Geolocalizado <span class="metavalue"><input type="checkbox" id="geolocalization" disabled="disabled" checked="checked" /></span></p>
					{% else%}
						<p class="metadata">Geolocalizado <span class="metavalue"><input type="checkbox" id="geolocalization" disabled="disabled" /></span></p>
					{% endif %}
		 		</ul>

				{% for section in form.section_set.all %}
					 <ul id="s{{ section.id }}" class="section" href="#s{{ section.id }}">
					   <p class="sectionlabel">{{ section.name }}</p>
					   {% for field in section.formfield_set.all %}
	                       <li id="f{{ field.id }}" class="{{ field.type|lower }}">
								<div class="actions">
									{% if field.required %}
										<img src="/beekeeper/images/buttons/required.png" class="fieldButton">
									{% endif %}
									<img src="/beekeeper/images/buttons/more.png" onclick="javascript:expandField('f{{ field.id }}')" class="fieldButton">
								</div>
	                       		<p class="fieldlabel">{{ field.label }}</p>
	                       		<br />
		                       {% if field.property_set.all %}
									<div class="properties">
								   {% for property in field.property_set.all %}
										<p>{{ property.name }}: {{ property.value }}</p>		                       		
								   {% endfor %}
			                       	</div>
		                       {% endif %}
		                       {% if field.fieldoption_set.all %}
									<div class="options">
								   {% for option in field.fieldoption_set.all %}
										<p>{{ option.label }}: {{ option.value }}</p>		                       		
								   {% endfor %}
			                       	</div>
		                       {% endif %}
	                       </li>
					   {% endfor %}
					</ul>
				{% endfor %}


				<br/>
			{% else %}
				<h3>No se ha encontrado el formulario en la base de datos.</h3>
			{% endif %}

{% endblock %}

{% block sidebar %}
		    <ul>
				<li><a class="item" href="/beekeeper/show_form_list/" id="campo0">
					<img src="/beekeeper/images/tw_back.png" />
					<div class="label">
						<p><strong>Volver atr&aacute;s</strong></p>
					</div>
				</a></li>	
				<li>
					<form name="elementDelete" class="item" action="/beekeeper/show_form/{{ form.id }}/" method="post">
						{% csrf_token %}
					    <input type="hidden" name="elementToDelete" value="{{ form.id }}" />
					    <input type="image" src="/beekeeper/images/tw_delete.png" name="submit" />
					   	<div class="label">
							<p><strong>Eliminar formulario</strong></p>
						</div>
						<!--<a href="document.elementDelete.submit();"><span class="tableelement"><img class="delete" src="/beekeeper/images/buttons/delete.png" /></span></a>-->
					</form>
				</li>
				
				<!-- <a class="item" href="/beekeeper/delete_form/{{ form.id }}" id="campo1">
					<img src="/beekeeper/images/delete.png" />
					<div class="label">
						<p><strong>Eliminar formulario</strong></p>
					</div>
				</a></li> -->
				<li><a class="item" href="/beekeeper/show_instance_list/{{ form.id }}" id="campo2">
					<img src="/beekeeper/images/tw_instances.png" />
					<div class="label">
						<p><strong>Instancias</strong></p>
					</div>
				</a></li>
				<li><a class="item" href="/beekeeper/show_form_statistics/{{ form.id }}" id="campo3">
					<img src="/beekeeper/images/tw_statistics.png" />
					<div class="label">
						<p><strong>Estad&iacute;sticas</strong></p>
					</div>
				</a></li>
				<li><a class="item" href="/beekeeper/show_instances_map/{{ form.id }}" id="campo4">
					<img src="/beekeeper/images/tw_geolocalization.png" />
					<div class="label">
						<p><strong>Geolocalizaci&oacute;n</strong></p>
					</div>
				</a></li>			
			</ul>
{% endblock %}


{% block sectionslinks %}
	<ul>
		<li id="s-1link">
			<a href="#s-1" onclick="selectSection('s-1')">
				Metadatos
			</a>
		</li>
	{% for section in form.section_set.all %}
		<li id="s{{ section.id }}link">
			<a href="#s{{ section.id }}" onclick="selectSection('s{{ section.id }}')">
				Sección {{ section.order }}
			</a>
		</li>
	{% endfor %}
	</ul>
	
{% endblock %}


{% block result %}
	{% if deleting %}
      <p class="enlaceeliminar">¿Desea eliminar el formulario y todas sus instancias? <br /><a href="/beekeeper/delete_form/{{ formToDelete }}">Sí, eliminar formulario.</a></p>
    {% endif %}
{% endblock %}


{% block extrajs %}
	{% if deleting %}
		<script language="JavaScript">
			$("#resultado").toggle('slow');
	    </script>
    {% endif %}
{% endblock %}

BeeKeeper/trunk/BeeKeeper/beekeeper/templates/ver_instancia.html
{% extends "base.html" %}
{% block title %}Formularios{% endblock %}
{% block mainframe %}

			{% if instance %}
				<h1>Instancia: {{ instance.id }}</h1>
				<h2>{{ instance.form.name }}</h2>


				<ul id="s-1" class="section" href="#s-1">
				   <p class="sectionlabel">Metadatos</p>
				   	{% if instance.creation_date %}
					  	<p class="metadata">Fecha de creaci&oacute;n: <span class="metavalue">{{ instance.creation_date }}</span></p>
					  	<p class="metadata">Fecha de modificaci&oacute;n: <span class="metavalue">{{ instance.modification_date }}</span></p>
					{% endif %}
				   	{% if instance.latitude %}
				   		<p class="metadata">Geolocalizaci&oacute;n</p>
					  	<p class="metadataSub">Latitud: <span class="metavalue">{{ instance.latitude }}</span></p>
						<p class="metadataSub">Longitud: <span class="metavalue">{{ instance.longitude }}</span></p>
					{% endif %}
				   	{% if instance.imei %}
					  	<p class="metadata">Imei</strong>: {{ instance.imei }}</p>
					{% endif %}
		 		</ul>

				{% for section in instance.form.section_set.all %}
					 <ul id="s{{ section.id }}" class="section" href="#s{{ section.id }}">
					   <p class="sectionlabel">{{ section.name }}</p>
					   {% for form_field in section.formfield_set.all %}
					   		{% for instance_field in instance_fields %}
						   		{% if instance_field.form_field.id == form_field.id %}

			                       	<li id="f{{ instance_field.id }}" class="{{ form_field.type|lower }}">
										<div class="actions">
											<img src="/beekeeper/images/buttons/more.png" onclick="javascript:expandField('f{{ instance_field.id }}')" class="fieldButton">
										</div>
										{% if instance_field.form_field.type == "IMAGE" %}
											<p> <span class="fieldlabel">{{ form_field.label }}</span>: <span class="fieldvalue"><img src="/beekeeper/media/{{ instance_field.get_text }}" /></span></p>
										{% else %}
											<p> <span class="fieldlabel">{{ form_field.label }}</span> : <span class="fieldvalue">{{ instance_field.get_text }} </span></p>
										{% endif %}
			                       		
			                       		<br />
		
				                       {% if form_field.property_set.all %}
											<div class="properties">
										   {% for property in form_field.property_set.all %}
												<p>{{ property.name }}: {{ property.value }}</p>		                       		
										   {% endfor %}
					                       	</div>
				                       {% endif %}
				                       {% if form_field.fieldoption_set.all %}
											<div class="options">
										   {% for option in form_field.fieldoption_set.all %}
												<p>{{ option.label }}: {{ option.value }}</p>		                       		
										   {% endfor %}
					                       	</div>
				                       {% endif %}

			                       </li>


		                       {% endif %}
	                       {% endfor %}
					   {% endfor %}
					</ul>
				{% endfor %}


				<br/>
			{% else %}
				<h3>No se ha encontrado el instanceulario en la base de datos.</h3>
			{% endif %}

{% endblock %}

{% block sidebar %}
		    <ul>
				<li><a class="item" href="/beekeeper/show_instance_list/{{ instance.form.id }}" id="campo0">
					<img src="/beekeeper/images/tw_back.png" />
					<div class="label">
						<p><strong>Volver atr&aacute;s</strong></p>
					</div>
				</a></li>	
				<li>
				    <form name="elementDelete" class="item" action="/beekeeper/show_instance/{{ instance.id }}/" method="post">
				        {% csrf_token %}
				        <input type="hidden" name="elementToDelete" value="{{ instance.id }}" />
				        <input type="image" src="/beekeeper/images/tw_delete.png" name="submit" />
						<!--<a href="document.elementDelete.submit();"><span class="tableelement"><img class="delete" src="/beekeeper/images/buttons/delete.png" /></span></a>-->
				    </form>
					<!-- <a class="item" href="/beekeeper/delete_instance/{{ instance.id }}" id="campo1"> 
					<img src="/beekeeper/images/delete.png" />
					<div class="label">
						<p><strong>Eliminar instanceulario</strong></p>
					</div>
					</a> -->
				</li>
				<li><a class="item" href="/beekeeper/show_instance_map/{{ instance.id }}" id="campo4">
					<img src="/beekeeper/images/tw_geolocalization.png" />
					<div class="label">
						<p><strong>Geolocalizaci&oacute;n</strong></p>
					</div>
				</a></li>			
			</ul>
{% endblock %}


{% block sectionslinks %}
	<ul>
		<li id="s-1link">
			<a href="#s-1" onclick="selectSection('s-1')">
				Metadatos
			</a>
		</li>
	{% for section in instance.form.section_set.all %}
		<li id="s{{ section.id }}link">
			<a href="#s{{ section.id }}" onclick="selectSection('s{{ section.id }}')">
				Sección {{ section.order }}
			</a>
		</li>
	{% endfor %}
	</ul>
	
{% endblock %}


{% block result %}
	{% if deleting %}
            <p class="enlaceeliminar">¿Desea eliminar la instancia? <br /><a href="/beekeeper/delete_instance/{{ instanceToDelete }}">Sí, eliminar la instancia.</a></p>
    {% endif %}
{% endblock %}


{% block extrajs %}
	{% if deleting %}
		<script language="JavaScript">
			$("#resultado").toggle('slow');
	    </script>
    {% endif %}
{% endblock %}