Seed/trunk/Seed/modeler/urls.py
from django.conf.urls.defaults import *
from django.conf import settings

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()


urlpatterns = patterns('',
    (r'css/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.CSS_MODELER_ROOT, 'show_indexes': False}),
    (r'images/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.IMAGES_MODELER_ROOT, 'show_indexes': False}),
    (r'js/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.JS_MODELER_ROOT, 'show_indexes': False}),
)

urlpatterns += patterns('modeler.views',
    (r'^$', 'showModeler'),
)

Seed/trunk/Seed/urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    (r'^modeler/', include('Seed.modeler.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # (r'^admin/', include(admin.site.urls)),
)

Seed/trunk/Seed/modeler/forms.py
'''
*Modeler Form* Request Modeler Form
   :author: Francisco Jose Cabrera Hernandez,
            Nicolas Pernas Maradei,
            Romen Rodriguez Gil
   :version: 0.1
'''
from django import forms

# Create your models here.

class NewForm(forms.Form):
    fieldList = forms.CharField()

Seed/trunk/Seed/modeler/views.py
'''
*Modeler Views* Views for Seed web modeler
   :author: Francisco Jose Cabrera Hernandez,
            Nicolas Pernas Maradei,
            Romen Rodriguez Gil
   :version: 0.1
'''
from django.shortcuts import render_to_response
from django.template import RequestContext
from Seed.modeler.forms import NewForm
from Seed.ws_client.beekeeperws import upload_new_form
from base64 import urlsafe_b64encode as sb64encode

#from xml.etree.ElementTree import tostring, XML

def showModeler(request):
    context = RequestContext(request)
    if request.method == 'POST':
        form = NewForm(request.POST)
        if form.is_valid() :
            xmlForm = form.cleaned_data['fieldList']
            xmlFormCleaned = sb64encode(xmlForm)
            errorMessage = ""
            try:
                response = upload_new_form(xmlFormCleaned)
            except:
                response = False
                errorMessage = "Error al enviar"
            #b64xml = sb64encode(unicode('<?xml version="1.0" encoding="UTF-8"?><form><id/><version>1</version><name>Formulario</name><author><user>turawet</user></author><sections><section><id/><name>Nombre seccion 0</name><fields><field><id /><label>Campo de texto</label><type>TEXT</type><properties/></field></fields></section></sections></form>'))
            #upload_new_form(b64xml)
            context['prueba'] = xmlForm
            context['prueba2'] = xmlFormCleaned
            context['wsresponse'] = response
            context['errormessage'] = errorMessage
#        if form.is_valid() :
#            return HttpResponseRedirect('/formList')
    else:
        form = NewForm()
        
    context['form'] = form
    return render_to_response('create.html', context)

#def parseSentFormXML (xml):
#    if xml is None:
#        return None
#    else:
#        #myparser = parseString(xml)
#        #sections = formXML.findall("section")
#        return xml;

Seed/trunk/Seed/ws_client/views.py
# Create your views here.

    
#from suds import WebFault

        
    #----------------- imp = Import('http://schemas.xmlsoap.org/soap/encoding/')
    #----------------------------- imp.filter.add('http://localhost:8000/soap/')
    #------------------------------------------------ doctor = ImportDoctor(imp)
    #--------------------------- client = Client(url, doctor=doctor, cache=None)
#------------------------------------------------------------------------------ 

Seed/trunk/Seed/modeler/templates/base.html
{% comment %}
Esquema basico de la web.
Project: Seed::Modeler
Author: Francisco Jose Cabrera Hernandez,
        Nicolas Pernas Maradei,
        Romen Rodriguez Gil
{% endcomment %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" href="images/modeler-favicon.ico" type="image/x-icon">
    <link rel="shortcut icon" href="images/modeler-favicon.ico" type="image/x-icon"> 
    <link rel="stylesheet" href="css/default.css" />
</head>
<body>
    <div id="containt">
        <div id="form">
            {% block mainframe %}
            {% endblock %}
        </div>
        
        <div id="resultado">
            <img class="delete" src="images/buttons/delete.png" onClick="hideResults()"/>
            {% block serviceresult %}
            {% endblock %}
        </div>
        
        <div id="sections">
            {% block sectionslinks %}
            {% endblock %}
        </div>

        <div id="fieldsBar">
            {% block sidebar %}
            {% endblock %}
            <div class="buttons">
                {% block buttonssidebar %}
                {% endblock %}
            </div>  
        </div>      
        <a href="http://www.turawetproject.org"><img src="images/tw_seed_logo.png" id="minilogo"/></a>
    </div>
    {% comment %}
        Librerías externas Javascript (JQuery y plugins)
    {% endcomment %}
    <script src="js/lib/jquery.min.js"></script>
    <script src="js/lib/jquery-ui.min.js"></script>
    <script src="js/lib/jquery.ndd.js"></script>
    <script src="js/lib/jquery.inlineedit.js"></script>
    {% comment %}
        Librerías javascript propias
    {% endcomment %}
    <script src="js/models.js"></script>
    <script src="js/fillform.js"></script>
    <script src="js/dragdrop.js"></script>
    <script src="js/parseform.js"></script>
    {% block extrajs %}
    {% endblock %}
</body>
</html>

Seed/trunk/Seed/modeler/templates/create.html
{% extends "base.html" %}

{% block title %}Turawet::Seed - Web Modeler{% endblock %}

{% block mainframe %}
	
	<h1 class="formname">Nombre del formulario</h1>
	<p id="labelgeo"><input type="checkbox" id="geolocalization"> Geolocalizado</p>
	<h2>Arrastra los campos al formulario</h2>
	<ul id="s0" class="section" href="#s0">
	  <p class="sectionlabel">Nombre de la secci&oacute;n 0</p>
	  <!--<li class="toEnd">
	      <p id="toEndText">Arrastra aqu&iacute; para a&ntilde;adir al final</p>
	  </li>-->
	</ul>
{% endblock %}
		
{% block serviceresult %}
    {% if wsresponse %}
      <!--<p class="prueba">Enviado:<br/>{{prueba}}</p>-->
      <p class="prueba">¡Formulario Guardado!</p>
    {% else %}
      <p class="prueba">Enviado:<br/>{{prueba}}</p>
      <p class="pruebaerror">{{errormessage}}</p>
    {% endif %}
{% endblock %}
		
{% block sectionslinks %}
    <ul>
        <li id="s0link"> <a href="#s0" onclick="selectSection(0)">Sección 0</a> </li>
    </ul>
{% endblock %}

{% block sidebar %}
    <ul>
		<li><a class="item" href="#" id="campo1" draggable="true">
		    <div class="type">text</div>
		    <div class="fieldtype">TEXT</div>
			<img src="images/fields/tw_icon_text.png" />
			<div class="label">
				<p><strong>Campo de texto</strong></p>
			</div>
		</a></li>
		<li><a class="item" href="#" id="campo2" draggable="true">
		    <div class="type">image</div>
		    <div class="fieldtype">IMAGE</div>
			<img src="images/fields/tw_icon_image.png" />
			<div class="label">
				<p><strong>Imagen</strong></p>
			</div>
		</a></li>
		<li><a class="item" href="#" id="campo3" draggable="true">
            <div class="type">radio</div>
            <div class="fieldtype">RADIO</div>
            <img src="images/fields/tw_icon_radio.png" />
            <div class="label">
                <p><strong>Radio Button</strong></p>
            </div>
        </a></li>
        <li><a class="item" href="#" id="campo4" draggable="true">
            <div class="type">date</div>
            <div class="fieldtype">DATE</div>
            <img src="images/fields/tw_icon_date.png" />
            <div class="label">
                <p><strong>Fecha</strong></p>
            </div>
        </a></li>
        <!-- <li><a class="item" href="#" id="campo6" draggable="true">
            <div class="type">location</div>
            <div class="fieldtype">LOCATION</div>
            <img src="images/base-button.png" />
            <div class="label">
                <p><strong>Geolocalización</strong></p>
            </div>
        </a></li> -->
        <li><a class="item" href="#" id="campo5" draggable="true">
            <div class="type">numeric</div>
            <div class="fieldtype">NUMERIC</div>
            <img src="images/fields/tw_icon_numeric.png" />
            <div class="label">
                <p><strong>Num&eacute;rico</strong></p>
            </div>
        </a></li>
        <!--<li><a class="item" href="#" id="campo7" draggable="true">
            <div class="type">textarea</div>
            <div class="fieldtype">TEXTAREA</div>
            <img src="images/base-button.png" />
            <div class="label">
                <p><strong>Área de texto</strong></p>
            </div>
        </a></li>-->
        <!--<li><a class="item" href="#" id="campo8" draggable="true">
            <div class="type">checkbox</div>
            <div class="fieldtype">CHECKBOX</div>
            <img src="images/base-button.png" />
            <div class="label">
                <p><strong>Checkbox</strong></p>
            </div>
        </a></li>
        <li><a class="item" href="#" id="campo9" draggable="true">
            <div class="type">combo</div>
            <div class="fieldtype">COMBO</div>
            <img src="images/base-button.png" />
            <div class="label">
                <p><strong>Combo</strong></p>
            </div>
        </a></li> -->  	
	</ul>
{% endblock %}

{% block buttonssidebar %}
	<a onclick="addSection(); return false" class="button white">
	    Nueva Secci&oacute;n
	</a>
    <br/>
    <form class="sendform" action="/modeler/" method="post">
        {% csrf_token %}
        <input type="hidden" name="fieldList" id="id_fieldList" />
        <!-- <button type="submit" name="sendButton" class="positive">-->
        <a class="button large green" onclick="fillForm(); this.parentNode.submit(); return false">
           Enviar
        </a>
        <!--<a class="button large red" onclick="showResults(); return false">
           <img src="images/bug.png"/>
        </a>-->
    </form>
{% endblock %}

{% block extrajs %}
	<!-- Debugging -->
	{% if prueba %}
	<script language="JavaScript">
            $("#resultado").toggle('slow');
    </script>
    {% endif %}
{% endblock %}